name = "LegendHDF5IO"
uuid = "c9265ca6-b027-5446-b1a4-febfa8dd10b0"
version = "0.1.8"

[deps]
ArraysOfArrays = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
EncodedArrays = "97725368-735e-11e9-0dd7-6bf34c3b13a8"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LegendDataTypes = "99e09c13-5545-5ee2-bfa2-77f358fb75d8"
RadiationDetectorSignals = "bf2c0563-65cf-5db2-a620-ceb7de82658c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
ArraysOfArrays = "0.5, 0.6"
ElasticArrays = "1"
EncodedArrays = "0.2, 0.3"
HDF5 = "0.15, 0.16, 0.17"
LegendDataTypes = "0.1"
RadiationDetectorSignals = "0.3"
StaticArrays = "0.12, 1.0"
StatsBase = "0.32, 0.33, 0.34"
StructArrays = "0.4, 0.5, 0.6"
Tables = "0.2, 1.0"
TypedTables = "1.2"
Unitful = "1"
julia = "1.6"
